### ISSUE TITLE
Error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dsoegijono** [lantanagroup/FHIR.js#53]
Sometimes I'm getting an exception when passing in invalid payload:

```
error: TypeError: Cannot read property 'split' of undefined
      at Validator.validateNext (/var/task/node_modules/fhir/validator.js:285:54)
      at Validator.validateProperties (/var/task/node_modules/fhir/validator.js:355:26)
      at Validator.validateNext (/var/task/node_modules/fhir/validator.js:268:36)
      at Validator.validateProperties (/var/task/node_modules/fhir/validator.js:347:34)
      at Validator.validateNext (/var/task/node_modules/fhir/validator.js:251:40)
      at Validator.validateProperties (/var/task/node_modules/fhir/validator.js:355:26)
      at Validator.validateNext (/var/task/node_modules/fhir/validator.js:303:18)
      at Validator.validateProperties (/var/task/node_modules/fhir/validator.js:347:34)
      at Validator.validate (/var/task/node_modules/fhir/validator.js:48:18)
      at Fhir.validate (/var/task/node_modules/fhir/fhir.js:42:26)
```

Is there a specific condition that causes this?

I'm using version 4.9.0

**Comment by seanmcilvenna** [comment]
Fixed in commit https://github.com/lantanagroup/FHIR.js/commit/be1a74cab134cff959fb0dc723c470a3e5443343
Published to NPM as 4.10.3
